

NewTaskInformation:
 TaskEmail: "Task - Email"
 TaskFax: "Task - Fax"
 TaskPhoneCalls: "Task - Phone Calls"
 TaskStandard: "Task - Standard"
 MyTasksSection: "My Tasks"
 TasksPriorityField: "Priority"
 TasksPriorityValue: "Normal"
 TasksStatusField: "Status"
 TasksStatusValue: "Not Started"
 TaskContactName: "smoke_test"
 TasksDueDateField: "Due Date"
 TasksDueDateValue: "11/13/2017"
 TasksSubjectField: "Subject"
 TasksCommentsField: "Comments"
 TaskRelatedTo: "smoke_test"
 TaskSubjectName: "Smoke_Test_Task_"
 TaskComments: "Smoke Testing"
 TasksRLMDetails: "RLM Details"
 TaskDirectionField: "Direction"
 TaskDirectionValue: "Incoming"
 TasksAssetField: "Asset"
 TasksTextBoxType: "text"
 TasksCheckBoxType: "checkbox"
 TaskHealthStatusReason: "Past due invoices"
 TasksStatusCompletedSuccessfully: "Completed Successfully"
 NoOpenTasksMessage: "You have no open tasks scheduled for this period"



NewQuotesInformation:
 NoOpportunitiesMessage: "No records to display."
 RenewalOpportunityTextBox: "text"
 OpportunityDetailsPage: "Opportunity Detail"
 NewOpportunityName: "Smoke_test_opportunity"
 NoOpportunityResults: "No matches found"
 OpportunityProduct: "test_product"
 NewQuoteName: "Smoke_Test_Quote_"
 QuoteTypeField: "Quote Type"
 QuoteTypeValue: "Direct"
 QuoteTypeYearField: "Quote Type Year"
 QuoteTypeYearValue: "2"
 QuoteDetailPage: "Quote Detail"
 SingleProductCheckboxIndex: "1"
 FindProductSearchButton: "Search"
 OpportunityProductName: "Test Product"
 ProductSelectButton: "Select"
 ProductQuantityField: "Quantity"
 ProductSalesPriceField: "Sales Price"
 ProductQuantity: "1"
 ProductSalesPrice: "100"
 QuotesStartDateField: "Start Date"
 QuotesEndDateField: "End Date"
 QuotesBatchTypeField: "Batch Type"
 QuoteSyncAttentionMessage: "Attention"
 QuoteSyncAttentionContinueButton: "Continue"
 QuoteStopSyncButton: "Stop Sync"
 QuoteLineItemDetailPage: "Quote Line Item Detail"
 FinancialAndCoverageDetailsSection: "Financial and Coverage Details"
 RelatedSectionNoRecordsMessage: "No records to display"



QuotesBatchTypePickListValues:
 QuotesBatchTypeExpired: "Expired"
 QuotesBatchTypeRenewal: "Renewal"
 QuotesBatchTypeAddsExpired: "Adds/Recovery Expired"
 QuotesBatchTypeAddsRenewal: "Adds/Recovery Renewal"
 QuotesBatchTypeAddsRecovery: "Adds/Recovery Uncovered"
 QuotesBatchTypeAdds: "Adds"

