Accounts:
  Field_Section: ["Number of Assets_Account Detail","Account Type_Account Detail","Customer Vertical_Account Detail","Customer Vertical Segment 2_Account Detail","Number of RLIs_Account Detail","Number of Opps_Account Detail","Billing Address_Account Detail","Shipping Address_Account Detail"]

